on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          package-name: release-please-action
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Update npm
        run: npm i -g npm@latest    
      - run: npm ci
      - run: npm run test
      - run: npm run build
      - run: npm publish --access public
        if: ${{ steps.release.outputs.release_created }}        